# Generated by Django 4.2.1 on 2023-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_cargo_rename_lon_location_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
