# Generated by Django 4.2.1 on 2023-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_cargo_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='zip',
            field=models.PositiveIntegerField(default=601),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargo',
            name='zip',
            field=models.PositiveIntegerField(default=601),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
